### ISSUE TITLE
Code Review for Yi Xin

### ISSUE THREAD

**Issue by sevenseasofbri** [AY2324S2-CS2113-T13-3/tp#121]
Reviewed some files for @Cryolian

In `InputParsing.java`:

- [x] In `promptForPhoneNumber` why not use exceptions instead of returning -1? The caller can then handle the error instead. Might be better for separation of concerns?
- [x] `invalidDatePath` doesn't seem like an apt name for a function. It should ideally be a verb.

**Comment by Cryolian** [comment]
Closed as completed
