### ISSUE TITLE
[PE-D][Tester A] Input Valid Phone Number Confusion

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T13-3/tp#182]
Unable to input phone number as specified in the user guide (12345678).

![Screenshot (119).png](https://raw.githubusercontent.com/BryanCastorius/ped/main/files/61c6c15b-33b2-43d2-99f7-42fd7b37deaf.png)

![Screenshot (120).png](https://raw.githubusercontent.com/BryanCastorius/ped/main/files/bece3505-4a37-43bf-8030-295ae2e0ad89.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: BryanCastorius/ped#2

**Comment by tayponghee** [comment]
Assigned: Gerard

Just need to update the value of the phone numbers that are allowed (8000_0000 to 9999_9999)
