### ISSUE TITLE
[PE-D][Tester D] Application does not recognize capitalized first letter commands for `edit` functionality.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T13-3/tp#190]
Not sure if this is intended, as the UG shows the command in lowercase but the prompt given by the application has the commands' first letter capitalized. This could be made clearer in the UG / app prompt, or perhaps the commands can be parsed such that both forms of input are accepted.

![image.png](https://raw.githubusercontent.com/clarencepohh/ped/main/files/b231de95-e483-40db-afb0-0bc2e0080f8f.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: clarencepohh/ped#2

**Comment by tayponghee** [comment]
Same as before
