### ISSUE TITLE
[PE-D][Tester C] Unable to view archived students

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T13-3/tp#199]
Can I clarify if there is a command to check the list of students who have been archived? The current implementation assumes that the user knows the archived student's name, but that may not be true as the user cannot view the archives?

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: RyanTDL/ped#3

**Comment by tayponghee** [comment]
Assigned: Shuihon, Parth and Gerard

Could be a big implementation, so see how yall want to do it
