### ISSUE TITLE
[PE-D][Tester B] list documentation bug

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T13-3/tp#203]
![image.png](https://raw.githubusercontent.com/ChinYanXu/ped/main/files/cc55d353-5580-4dd0-86bf-2de114a4a631.png)

documentation for the list feature states the command format to be "list, enter, enter, number". "enter, enter" seems to be a typo and should be deleted

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ChinYanXu/ped#4

**Comment by tayponghee** [comment]
Assigned: Parth

See how u want to format this cause this is how the list function works
