### ISSUE TITLE
[PE-D][Tester B] character "-" will not always result in a bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T13-3/tp#207]
![image.png](https://raw.githubusercontent.com/ChinYanXu/ped/main/files/7ac4805e-1c61-419a-b9ec-fbe27839bf36.png)

![image.png](https://raw.githubusercontent.com/ChinYanXu/ped/main/files/dbe78f5c-e59d-4d6d-be3a-bee2bfb027cd.png)

In the documentation, "-" is listed as one of the characters that will be replaced if it is included in a string input. However when "-" is included into "math-sci" during the add subject phase of the adding interface, not error occurs and "math-sci" is stored successfully.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: ChinYanXu/ped#5

**Comment by tayponghee** [comment]
Assigned: Shui Hon

Update the UG to explain the situations in which the - is allowed

**Comment by Cryolian** [comment]
Closed as - is now always banned, and never allowed.
